### ISSUE TITLE
big.gv fails

### ISSUE THREAD

**Issue by levnach** [anvaka/dotparser#17]
This file is successfully processed by dot.exe. dotparser fails with the message

✖ Expected "\"" or "\\" but "\n" found.

  grammar/dot.js

  519 |   function peg$buildStructuredError(expected, found, location) {
                                   ror(
      | -----------^
              peg$SyntaxError.buildMessage(expected, found),

  test: big.gv
  stack: |
    peg$buildStructuredError (grammar/dot.js:520:12)
    peg$parse (grammar/dot.js:2938:11)
    Test.<anonymous> (test/index.js:9:13)
  type: SyntaxError
  expected:
    - &a1
      type: literal
      text: \
      ignoreCase: false
    - *a1
    - type: literal
      text: '"'
      ignoreCase: false
  found: "\n"
  location:
    start:
      offset: 215
      line: 5
      column: 50
    end:
      offset: 216
      line: 6
      column: 1
  tapCaught: testFunctionThrow.

It fails on a long string that begins like that: 
 struct3 [shape=record,label="hello\nworld\n\
and  | { Thats the reason | post-menopausal | 

The graph is "big.gv" of Graphvis collection. I am not sure how to share it with you, cannot find it on the web at the moment. Let me know if it is a problem and I will share it.

**Comment by anvaka** [comment]
Thank you for sharing, Lev. 

I tested against https://github.com/ellson/MOTHBALLED-graphviz/blob/master/rtest/graphs/big.gv and was able to parse it using https://github.com/anvaka/dotparser/blob/master/test/parseGraphVizSuite.js 

I see that file contains `\n` syntax, and wonder maybe it has a different meaning depending on how you load it. For example, if you open a javascript console in a browser and type 

``` js
> console.log("hello\nworld")
hello
world
```

You get a multiline text. However if you create a file `foo.txt` and put the same `hello\nworld` into it, and then run from node:

``` js
> console.log(require('fs').readFileSync('foo.txt', 'utf8'))
hello\nworld
```

The `\n` will be printed as is, and the test passes just fine. 

Are you running into this issue in a browser? How do you pass the `big.gv` content to the parser?

**Comment by levnach** [comment]
Andrei! Мир тесен!
This is my typescript code 
const graphStr = readFileSync(fileName, 'utf-8')
const ast = parse(graphStr)

**Comment by levnach** [comment]
It just started working after I bumped up some Node packages versions. I am not sure what exactly caused the change.
