### ISSUE TITLE
.d.ts 

### ISSUE THREAD

**Issue by levnach** [anvaka/dotparser#18]
Hi Andrei, 
I consume your very useful dotparser in a typescript project. Ideally I need the type files for it.
Can you generate them please?
Thanks,
Lev

**Comment by anvaka** [comment]
Hi Lev, I can take a look later this weekend unless someone else wants to do it sooner 

(CC @fecorreiabr who was submitting types for a few ngraph libraries lately)

**Comment by fecorreiabr** [comment]
I don't know much about GraphViz dot format, but I wrote a declaration file according to the source: https://github.com/fecorreiabr/dotparser/blob/types/index.d.ts
@anvaka please check it out and let me know if it's ok so I can create a pull request.

**Comment by anvaka** [comment]
It does look good to me!
If you send a PR I'd gladly merge it!


Thank you @fecorreiabr

**Comment by anvaka** [comment]
@fecorreiabr thank you for the wonderful quick response!

@levnach this should be published in `v1.1.0`. Please let us know if you find anything missing.

**Comment by levnach** [comment]
I think there is a problem with the new version. After installing the new package and changing 
import parse = require('dotparser') 
to 
import parse from 'dotparser',
 I am getting a run-time error: 
TypeError: dotparser_1.default is not a function

**Comment by anvaka** [comment]
Lev, looks like you need to pass `--esModuleInterop` to the typescript compiler if you want to use `import` directive instead of `require()`.

Found answer here https://stackoverflow.com/questions/61524130/typescript-babel-import-causing-1-default-is-not-a-function - verified that it is working with `dotparser`

**Comment by levnach** [comment]
It works! Thanks!
