### ISSUE TITLE
Stmt is not full

### ISSUE THREAD

**Issue by levnach** [anvaka/dotparser#21]
Please change line 
https://github.com/anvaka/dotparser/blob/bd04dc9e29683f94eb92367f9084a81ba1c9de89/index.d.ts#L3
to 
`export type Stmt = AttrStmt | EdgeStmt | NodeStmt | Subgraph;`

I tried using the type hierarchy in Typescript code and I think found a bug.

**Comment by anvaka** [comment]
Thank you! This should be published as `v1.1.1`
