### ISSUE TITLE
An empty subgraph generates an incorrect ast

### ISSUE THREAD

**Issue by magjac** [anvaka/dotparser#5]
This is an very minor issue in an extreme corner case, but nevertheless...

This dot:
```
digraph {
    subgraph s1 {}
}
```
generates:
```
[
    {
        "type": "digraph",
        "children": [
            {
                "type": "subgraph",
                "id": "s1",
                "children": []
            },
            {
                "type": "subgraph",
                "children": null
            }
        ]
    }
]
```
So there is two subgraphs in the ast when there should be only one. The first one is correct, but the second is not.

The unnamed subgraph:
```
digraph {{}}
```
generates:
```
[
    {
        "type": "digraph",
        "children": [
            {
                "type": "subgraph",
                "children": null
            }
        ]
    }
]
```
which contains only the erroneous subgraph.

If a node is added to the named subgraph:
```
digraph {subgraph s1{a}}
```
the ast is correct:
```
[
    {
        "type": "digraph",
        "children": [
            {
                "type": "subgraph",
                "id": "s1",
                "children": [
                    {
                        "type": "node_stmt",
                        "node_id": {
                            "type": "node_id",
                            "id": "a"
                        },
                        "attr_list": []
                    }
                ]
            }
        ]
    }
]
```

**Comment by anvaka** [comment]
Thanks for reporting this!

> digraph {{}}

Younger me thought it was a correct use case for anonymous subgraphs: https://github.com/anvaka/dotparser/issues/2

I need to refresh my knowledge of pegjs grammar to fix the issue that you've reported. If anyone wants to help fixing this - I'd really appreciate the help!

**Comment by magjac** [comment]
I've opened a new PR with a fix. The commit references above looks a little strange, because I deleted the branch and start all over after rebasing on your latest changes.

Since I removed two constructs in the pegjs, maybe it would be a good idea to add some more tests before merging, if you can't remember what the younger you had in mind with those constructs :smile:.
